config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  get 'pages/secret'
  resources :users, only: [:index, :new, :create, :destroy]
  resources :user_sessions, only: [:new, :create, :destroy]
  resources :articles
  # resources :user_sessions, only: [:new, :create, :destroy]

  # get 'users/index'
  # get 'users/new'
  # get 'users/create'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password :password, validations: true
    validates :name, presence: true, uniqueness: true
    has_many :articles, dependent: :destroy
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user 
    # global defination of a variable

    def current_user
        # If session[:user_id] is nil, set it to nil, otherwise find the user by id.

        @current_user ||= session[:user_id] && User.find_by(id: session[:user_id])
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = current_user.articles.build
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @article = current_user.articles.build(article_params)
    if @article.save
      redirect_to @article, notice: 'Article was successfully created.'
    else
      render :new
    end
  end

  def update
    @article=Article.find(params[:id])
    if @article.update(article_params)
      redirect_to @article, notice: 'Article was modified.'
    else
      render :edit
    end
  end
  
  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to root_path, status: :see_other
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def authorize_user!
    redirect_to articles_path, alert: 'You are not authorized to edit this article' unless @article.user == current_user
  end

  def article_params
    params.require(:article).permit(:title, :body)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def secret
    if current_user.blank?
      render plain: '401 Unauthorized', status: :unauthorized
    end
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.find_by(name: params[:user][:name])

    if @user && @user.authenticate(params[:user][:password])
      session[:user_id] = @user.id 
      # method provided by rails to recognise whether a user who has logged in 
      redirect_to root_path
    else
      flash[:alert] = "Login failed"
      redirect_to new_user_session_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      @user = User.find_by(name: params[:user][:name])
      if @user && @user.authenticate(params[:user][:password])
        session[:user_id] = @user.id 
        flash[:notice] = "User created successfully"
        # method provided by rails to recognise whether a user who has logged in 
        redirect_to root_path
      end
    else
      flash[:alert] = "User not created"
      render :new, status: :unprocessable_entity
    end
  end


  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to root_path, status: :see_other
  end

  private
  
  def user_params
    params.require(:user).permit(:name, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
<%= form_with(model: article, local: true) do |form| %>
    <% if article.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>
        <ul>
          <% article.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="field">
      <%= form.label :title %>
      <%= form.text_field :title %>
    </div>
  
    <div class="field">
      <%= form.label :body %>
      <%= form.text_area :body %>
    </div>
      
  
    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>
  

app/views/articles/edit.html.erb
<h1>Edit Article</h1>
<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Articles</h1>
<% if current_user %>
  <%= link_to 'New Article', new_article_path %>
<% end %>
<% @articles.each do |article| %>
  <h2><%= link_to article.title, article_path(article) %></h2>
  <p><%= truncate(article.body, length: 100) %></p>
<% end %>

app/views/articles/new.html.erb
<h1>New Article</h1>
<%= render 'form', article: @article %>
<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<p><%= @article.body %></p>
<p>
  <%= link_to 'Edit', edit_article_path(@article) if @article.user == current_user %> 
  <li><%= link_to "Delete", article_path(@article), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
  <%= link_to 'Back', articles_path %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AuthFromScratch</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
   <% flash.each do |type, msg| %>
    <div>
      <%= msg %>
    </div>
    <%end%>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<% if current_user %>
  <h1>Welcome, <%= current_user.name %></h1>
  <%= link_to 'Log out', user_session_path(current_user), data: { turbo_method: :delete } %><br>
  <%= link_to 'Articles', articles_path %><br>
  <li><%= link_to "Delete", user_path(current_user), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
<% else %>
  <h1>This is the index page</h1>
  <%= link_to 'Login', new_user_session_path %><br>
  <%= link_to 'Sign Up', users_path %><br>

<% end %>
<%= link_to 'Secret page', '/pages/secret' %>

app/views/pages/secret.html.erb
<h1>THIS IS A SECRET PAGE</h1>

<p>The world's first computer programmer was a woman named Ada Lovelace.
</p>

app/views/user_sessions/create.html.erb
<h1>UserSessions#create</h1>
<p>Find me in app/views/user_sessions/create.html.erb</p>

app/views/user_sessions/new.html.erb
<h1>Login page</h1>
<%= form_with model: @user, url: user_sessions_path do |f| %>
  <div>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <p>
    <%= f.submit 'Login' %>
  </p>
<% end %>

app/views/users/create.html.erb
<h1>Users</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/index.html.erb
<h1>Users</h1>

<%= link_to 'New User', new_user_path %>

<table>
  <thead>
    <tr>
      <th>id</th>
      <th>name</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<h1>Users</h1>
<%= form_with model: @user do |f| %>
  <% if @user.errors.any? %>
    <div>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <p>
    <%= f.submit %>
  </p>
<% end %>